### ISSUE TITLE
fix rendering

### ISSUE THREAD

**Issue by MicahBear** [MicahBear/express-node-post#2]
# Overview
currently server file is handling response for json data if we were setting up for api.

## Action
- [x] Install client side code in a client folder
- [x] complete a fetch call from client side
- [x] render data from fetch call to UI

### notes

- [ ] Update Assignees to right 
- [ ] Make sure right project is selected: Node-Express-Postgres
- [ ] Update status to in-progress

**Comment by Gowtham1403** [comment]
Completed
